### Numpy: Following the Numpy User Guide

In [1]:
import numpy as np

In [2]:
a = np.array([[2,3,4],[5,6,7]])
print(a)
a.shape


[[2 3 4]
 [5 6 7]]


(2, 3)

In [3]:
# Accessing element using row and column index position
a[0,0] # outputs 2, the first element of the 2 dimensional ndarray [row,column]

np.int64(2)

In [4]:
print(a.ndim)
print(a.dtype)

2
int64


In [5]:
# 1D (vector)
a = np.zeros(2)
print('a',a)  # (2,)
print('\n')

# 2D (matrix)
b = np.zeros((2, 3))
print('b',b)  # (2, 3)
print("\n")

# 3D (tensor)
c = np.zeros((2, 3, 4))
print('c',c)

a [0. 0.]


b [[0. 0. 0.]
 [0. 0. 0.]]


c [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [6]:
np.ones((2,4),dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [7]:
np.empty((3, 4))  # creates an array whose initial content is random and depends on the state of the memory

array([[0.00000000e+000, 0.00000000e+000, 6.12839552e-310,
        6.12839552e-310],
       [1.95348647e-315, 4.85237681e-317, 6.12839552e-310,
        4.85428983e-317],
       [6.12841128e-310, 6.12841129e-310, 6.12839552e-310,
        6.12841035e-310]])

In [8]:
a = np.arange(5)  # create an array with a range of elements
print(a)

b = np.arange(2, 9, 2)  # contains a range of evenly spaced intervals.,specify the first number, last number, and the step size.
print(b)

[0 1 2 3 4]
[2 4 6 8]


In [9]:
np.linspace(0,10,6,dtype=np.int64)  # create an array with values that are spaced linearly in a specified interval

array([ 0,  2,  4,  6,  8, 10])

In [10]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [11]:
np.sort(arr,stable=True) #  np.sort(arr) also works fine

array([1, 2, 3, 4, 5, 6, 7, 8])

### Concatenation

For a 1D array: only axis = 0. Only increases the length of the array (column-wise).


For a 2D array:


      axis=0 → rows (downwards, vertical direction).
            ie :
                  [[1 2]
                  [3 4]
                  [5 6]
                  [7 8]]

      axis=1 → columns (across, horizontal direction).
            ie :
                  [[1 2 5 6]
                  [3 4 7 8]]


For a 3D array:  a cube → axis=0 (different cubes), axis=1 (rows inside each cube), axis=2 (columns inside each cube)

      axis=0 → stacks along the first dimension (depth).
            ie :
                  [[[1 2]
                  [3 4]]
                  
                  [[5 6]
                  [7 8]]]

      axis=1 → stacks along the second dimension (height).
            ie :
                  [[[1 2]
                  [3 4]]
                  
                  [[5 6]
                  [7 8]]]

      axis=2 → stacks along the third dimension (width).
            ie :
                  [[[1 2 5 6]
                  [3 4 7 8]]]

For a 4D array:  Shape = (batch, channels, height, width)
      axis=0 → stacks along the batch dimension.
            ie :
                  [[[[1 2]
                  [3 4]]]
                  
                  [[[[5 6]
                  [7 8]]]]

      axis=1 → stacks along the channels dimension.
            ie :
                  [[[[1 2]
                  [3 4]]
                  
                  [[5 6]
                  [7 8]]]]

      axis=2 → stacks along the height dimension.
            ie :
                  [[[[1 2]
                  [3 4]]
                  
                  [[5 6]
                  [7 8]]]]

      axis=3 → stacks along the width dimension.
            ie :
                  [[[[1 2 5 6]
                  [3 4 7 8]]]]

            



General Rule:

axis=0 → stack vertically (increase rows).

axis=1 → stack horizontally (increase columns).
            

In [17]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
z = np.concatenate((a, b))


In [13]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])


np.concatenate((x, y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
x = np.array([[1, 2]])
y = np.array([[5, 6]])

z = np.concatenate((x,y),axis=1)

print(x)
print(z)

print('x shape prints:',x.shape)
print('Z shape prints :',z.shape)

[[1 2]]
[[1 2 5 6]]
x shape prints: (1, 2)
Z shape prints : (1, 4)


In [15]:
# 3-Dimentional Array

a = np.array([[[1, 2], [3, 4]]])

b = np.array([[[5, 6], [7, 8]]])

z = np.concatenate((a,b), axis=0)
# The following is only true with axis = 0
# shape = (2, 2, 2)
# [[[1 2]   [[[5 6]
#   [3 4]],   [7 8]]]

print(a)
print("\n\n\n")
print(z)

print("a shape prints:", a.shape)
print("Z shape prints :", z.shape)

[[[1 2]
  [3 4]]]




[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
a shape prints: (1, 2, 2)
Z shape prints : (2, 2, 2)


In [16]:
z[1,0]

array([5, 6])