### Numpy: Following the Numpy User Guide

In [1]:
import numpy as np

In [15]:
a = np.array([[2,3,4],[5,6,7]])
print(a)
a.shape


[[2 3 4]
 [5 6 7]]


(2, 3)

In [17]:
# Accessing element using row and column index position
a[0,0] # outputs 2, the first element of the 2 dimensional ndarray [row,column]

np.int64(2)

In [20]:
print(a.ndim)
print(a.dtype)

2
int64


In [27]:
# 1D (vector)
a = np.zeros(2)
print('a',a)  # (2,)
print('\n')

# 2D (matrix)
b = np.zeros((2, 3))
print('b',b)  # (2, 3)
print("\n")

# 3D (tensor)
c = np.zeros((2, 3, 4))
print('c',c)

a [0. 0.]


b [[0. 0. 0.]
 [0. 0. 0.]]


c [[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [48]:
np.ones((2,4),dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
np.empty((3, 4))  # creates an array whose initial content is random and depends on the state of the memory

array([[4.69426062e-315, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 3.89113968e-033, 8.30282495e-067,
        5.69618614e-066],
       [6.52857652e-038, 9.16892709e-072, 9.51188833e+169,
        2.57895217e-057]])

In [38]:
a = np.arange(5)  # create an array with a range of elements
print(a)

b = np.arange(2, 9, 2)  # contains a range of evenly spaced intervals.,specify the first number, last number, and the step size.
print(b)

[0 1 2 3 4]
[2 4 6 8]


In [47]:
np.linspace(0,10,6,dtype=np.int64)  # create an array with values that are spaced linearly in a specified interval

array([ 0,  2,  4,  6,  8, 10])

In [49]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [51]:
np.sort(arr,stable=True) #  np.sort(arr) also works fine

array([1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

np.concatenate((x, y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])